# Анализ данных

Хранилище

* Хранение
    
        Таблицы 4: 
    
            Ожидаемые поставки за Декабрь 2020, Январь и Аперль 2021
 
 
* Обработка
    * План на вход
            
            Таблица 3:
            
                План БС в штуках
    
            Таблица 6: 
    
                Приходные операции за 2020-2021
    
    
    * План на выход
    
            Таблица 5: 
    
                Расходные операции за 2021

In [1]:
import pandas as pd

In [2]:
data_apr = pd.read_excel('../data/4.Ожидаемые поставки_Апрель2021.xlsx', sheet_name=0, skiprows=3)
data_jan = pd.read_excel('../data/4.Ожидаемые поставки_Январь2021.xlsx', sheet_name=1)
data_dec = pd.read_excel('../data/4.Ожидаемые поставки_Декабрь2020.xlsx',sheet_name=1)

In [3]:
data_apr.head()

,Номер строки в заказе/релизе,Код позиции ЕНС,Наименование позиции ЕНС,Единица измерения,Заказанное количество,Полученное количество,В пути,Организация-получатель,Объём,Общий объём,Дата исполнения заказа/договора,м3,Дата исполнения заказа/договора*,Месяц,Год,Дата поставки SWAP Эрикссон
0,1,160.346.000041,"Блок внутренний IDU Huawei RTN 910AF, 2хGE RJ4...",штука,34,0,34,101,"0,05",1.700000,13.05.2021,0.000000,25.04.2021,4.0,2021.0,00:00:00
1,2,249.022.000011,"Приемопередатчик оптический (eSFP, 1310нм, 1.2...",штука,136,0,136,101,0.000448,0.060928,13.05.2021,0.000448,25.04.2021,4.0,2021.0,00:00:00
2,3,161.346.000136,"Радиоблок внешний ODU Huawei RTN XMC-5D 18ГГц,...",штука,8,0,8,101,0.02,0.160000,13.05.2021,0.023273,25.04.2021,4.0,2021.0,00:00:00
3,4,161.346.000137,"Радиоблок внешний ODU Huawei RTN XMC-5D 18ГГц,...",штука,8,0,8,101,0.02,0.160000,13.05.2021,0.023273,25.04.2021,4.0,2021.0,00:00:00
4,5,161.346.000132,"Радиоблок внешний ODU Huawei RTN XMC-5D 18ГГц,...",штука,9,0,9,101,0.02,0.180000,13.05.2021,0.021888,25.04.2021,4.0,2021.0,00:00:00

In [5]:
data_jan.head()

,Номер строки в заказе/релизе,Код позиции ЕНС,Наименование позиции ЕНС,Единица измерения,Заказанное количество,Полученное количество,В пути,Длина,Ширина,Высота,Объём,Общий объём,Организация-получатель,Дата исполнения заказа/договора,Группа,Наименовнание группы,БС,Месяц,Год
0,1.0,204.346.000194,Карта 12-портовая интерфейсная 10GBase LAN/WAN...,штука,2.0,0.0,2.0,",05",",2",",2",",002",0.004,702,26.01.2021,204.0,Мультиплексоры,0,1.0,2021.0
1,2.0,249.022.000342,Материнский модуль для линейных плат (тип LPUF...,штука,2.0,0.0,2.0,",75",",56",",17",",0714",0.1428,702,26.01.2021,249.0,Мультиплексоры,0,1.0,2021.0
2,1.0,249.022.000301,Карта мультиплексора Flexible Card Line Proces...,штука,1.0,0.0,1.0,",17",",57",",75",",072675",0.072675,702,12.01.2021,249.0,Мультиплексоры,0,1.0,2021.0
3,2.0,249.022.000302,Карта 6-портовая 6-Port 10GBase LAN/WAN-SFP+ F...,штука,1.0,0.0,1.0,",09",",26",",34",",007956",0.007956,702,12.01.2021,249.0,Мультиплексоры,0,1.0,2021.0
4,1.0,181.022.000004,Инсталяционные материалы Huawei для ODU XMC-5D...,штука,24.0,0.0,24.0,",38",",23",",1",",00874",0.20976,304,15.03.2021,181.0,РРЛ,0,3.0,2021.0

In [6]:
data_dec.head()

,Дата создания заказа,Дата утверждения заказа,Номер контракта,Номер строки в заказе/релизе,Код позиции ЕНС,Наименование позиции ЕНС,Единица измерения,Заказанное количество,Полученное количество,В пути,Длина,Ширина,Высота,Объём,Общий объём,Организация-получатель,Дата исполнения заказа/договора
0,2021-11-18,2021-12-21,NaN,4,249.022.000267,Оптический приемопередатчик SFP+ 1310nm 10Gb/s...,штука,164,0,164,",08",",01",",01",",000008",",001312",К05,02.02.2022
1,2021-11-18,2021-12-21,NaN,5,249.022.000251,Оптический приемопередатчик SFP+ 1550nm 9.95-1...,штука,50,0,50,",1",",02",",02",",00004",",002",К05,02.02.2022
2,2021-08-27,2021-09-15,D1003239_15(17),1,161.346.000100,"Блок внешний РРЛ Huawei RTN 380AX, 80ГГц, 3Гби...",штука,50,0,50,",1",",38",",58",",02204","1,102",107,29.01.2022
3,2021-08-27,2021-09-15,D1003239_15(17),2,161.346.000099,"Блок внешний РРЛ Huawei RTN 380AX, 80Ггц, 3Гби...",штука,50,0,50,",1",",38",",58",",02204","1,102",107,29.01.2022
4,2021-08-27,2021-09-15,D1003239_15(17),3,181.022.000001,Разъем питания Huawei для RTN 380 Power connec...,штука,100,0,100,",38",",1",",23",",00874",",874",107,29.01.2022

## Убираем ненужные колонки
Причина: Содержат дополнительную информацию, имеющую доплнительную или дублирующую функции

Например:

**Доп информация**: Единица измерения или Наименование позиции ЕНС

**Дублируюущая**: Дата исполнения заказа/договора

In [7]:
drop_apr = [
    'Номер строки в заказе/релизе', 
    'Наименование позиции ЕНС',
    'Единица измерения',
    'Полученное количество', 
    'В пути',
    'Дата исполнения заказа/договора', 
    'м3',
    'Дата исполнения заказа/договора*',
    'Дата поставки SWAP Эрикссон',
]

drop_jan = [
    'Номер строки в заказе/релизе',
    'Наименование позиции ЕНС', 
    'Единица измерения',
    'Полученное количество', 
    'В пути', 
    'Длина',
    'Ширина', 
    'Высота', 
    'Дата исполнения заказа/договора', 
    'Группа', 
    'Наименовнание группы',
    'БС',
]

drop_dec = [
    'Дата создания заказа',
    'Номер контракта',
    'Номер строки в заказе/релизе',
    'Наименование позиции ЕНС',
    'Единица измерения',
    'Полученное количество', 
    'В пути', 
    'Длина',
    'Ширина', 
    'Высота',
]

data_apr.drop(drop_apr, axis=1, inplace=True)
data_jan.drop(drop_jan, axis=1, inplace=True)
data_dec.drop(drop_dec, axis=1, inplace=True)

**Посмотрим на то, какие данные содержатся в датасетах**

In [8]:
# Датасет за апрель
data_apr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4976 entries, 0 to 4975
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Код позиции ЕНС         4976 non-null   object
 1   Заказанное количество   4976 non-null   int64
 2   Организация-получатель  4976 non-null   object
 3   Объём                   4976 non-null   object
 4   Общий объём             4976 non-null   float64
 5   Месяц                   4511 non-null   float64
 6   Год                     4511 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 272.2+ KB

In [9]:
# Датасет за январь
data_jan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3756 entries, 0 to 3755
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Код позиции ЕНС         3749 non-null   object
 1   Заказанное количество   3749 non-null   float64
 2   Объём                   3585 non-null   object
 3   Общий объём             3565 non-null   object
 4   Организация-получатель  3752 non-null   object
 5   Месяц                   3749 non-null   float64
 6   Год                     3749 non-null   float64
dtypes: float64(3), object(4)
memory usage: 205.5+ KB

In [10]:
# Датасет за декабрь
data_dec.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5002 entries, 0 to 5001
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Дата утверждения заказа          4409 non-null   datetime64[ns]
 1   Код позиции ЕНС                  5002 non-null   object
 2   Заказанное количество            5002 non-null   int64
 3   Объём                            4848 non-null   object
 4   Общий объём                      4651 non-null   object
 5   Организация-получатель           5002 non-null   object
 6   Дата исполнения заказа/договора  4273 non-null   object
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 273.7+ KB

Видно, что *'Дата исполнения заказа/договора'* в *датасете за декабрь* имеет не тот тип данных, котоирый нам нужен.

In [11]:
"""
Переводим object в формат datetime и парсим колонку 'Дата исполнения заказа/договора'  
на значения год и месяц и создаем новые колонки с аналогичным названием
"""


data_dec['Дата исполнения заказа/договора'] = \
data_dec['Дата исполнения заказа/договора'].apply(lambda x: pd.to_datetime(x, dayfirst=True))

data_dec['Год'] = pd.DatetimeIndex(data_dec['Дата исполнения заказа/договора']).year
data_dec['Месяц'] = pd.DatetimeIndex(data_dec['Дата исполнения заказа/договора']).month

data_dec.drop(['Дата исполнения заказа/договора', 'Дата утверждения заказа'], axis=1, inplace=True)

## Выводим уникальные значения

In [12]:
data_jan['Год'].unique()

array([2021., 1900., 2020., 2018., 2019., 2015.,   nan])

In [13]:
data_dec['Год'].unique()

array([2022., 2021.,   nan, 2023., 2020., 2019.])

In [14]:
data_apr['Год'].unique()

array([2021.,   nan, 2020.])

Из ячеек сверху видно, что в датасетах есть *лишние* года

Например, в отчете за январь 2021 года есть строки, включающие 1900 год.

In [30]:
# Замена на нужный год

data_jan['Год'] = data_jan['Год'].astype(str).replace('1900|2020|2018|2019|2015', '2021', regex=True)
data_dec['Год'] = data_dec['Год'].astype(str).replace('2022|2021|2023|2019', '2020', regex=True)
data_apr['Год'] = data_apr['Год'].astype(str).replace('2020', '2021', regex=True)

In [31]:
data_jan['Год'].unique()

array(['2021.0', 'nan'], dtype=object)

In [32]:
data_jan[data_jan['Год'] == 'nan']

,Код позиции ЕНС,Заказанное количество,Объём,Общий объём,Организация-получатель,Месяц,Год
3749,NaN,NaN,NaN,NaN,NaN,NaN,nan
3750,NaN,NaN,NaN,NaN,NaN,NaN,nan
3751,NaN,NaN,NaN,NaN,NaN,NaN,nan
3752,NaN,NaN,NaN,NaN,NaN,NaN,nan
3753,NaN,NaN,NaN,Прогноз,февр,NaN,nan
3754,NaN,NaN,NaN,Шкаф дом узла,1207,NaN,nan
3755,NaN,NaN,NaN,NaN,187м3,NaN,nan

In [33]:
data_apr[data_apr['Год'] == 'nan']

,Код позиции ЕНС,Заказанное количество,Организация-получатель,Объём,Общий объём,Месяц,Год
1091,160.346.000041,100,101,"0,05",5.000000,NaN,nan
1092,249.022.000011,400,101,0.000448,0.179200,NaN,nan
1093,161.346.000136,22,101,0.02,0.440000,NaN,nan
1094,161.346.000137,22,101,0.02,0.440000,NaN,nan
1095,161.346.000132,28,101,0.02,0.560000,NaN,nan
...,...,...,...,...,...,...,...
4939,181.346.000278,3,101,0.032,0.096000,NaN,nan
4940,159.179.000732,5,702,0.0045,0.022500,NaN,nan
4941,160.179.000320,5,702,0.0045,0.022500,NaN,nan
4942,213.179.000006,25,702,0.000005,0.000131,NaN,nan
4943,181.346.000230,5,702,0.000012,0.000060,NaN,nan

# ML алгоритм линейная регрессия

На вход в алгоритм подается: объем планируемых поставок за определенный период

На выходе: объем резервации